spring:
  config:
    activate:
      on-profile: local
  custom-datasource:
    url: jdbc:postgresql://localhost:5432/gym_db
    username: postgres
    password: 4999
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info